import {
	connectStateClasses,
	createAdCountdown,
	createAdLabel,
	createAdOverlay,
	createAdSkip,
	createAdUIState,
	createAutohide,
	createBigPlay,
	createClickPlay,
	createErrorDisplay,
	createFullscreen,
	createKeyboard,
	createLoader,
	createPlayButton,
	createPoster,
	createProgress,
	createTimeDisplay,
	createVolume,
	formatTime,
	isAdState,
	stateToClass,
	ui,
	uiAdPlugin,
} from "../ui/index.js";

// biome-ignore lint/suspicious/noExplicitAny: global namespace access
// biome-ignore lint/suspicious/noAssignInExpressions: intentional ??= for global namespace init
const ns = ((globalThis as any).Vide ??= {});
Object.assign(ns, {
	ui,
	createPlayButton,
	createProgress,
	createTimeDisplay,
	createVolume,
	createFullscreen,
	createLoader,
	createErrorDisplay,
	createBigPlay,
	createPoster,
	createAdCountdown,
	createAdSkip,
	createAdOverlay,
	createAdLabel,
	createKeyboard,
	createClickPlay,
	createAutohide,
	connectStateClasses,
	stateToClass,
	isAdState,
	formatTime,
	createAdUIState,
	uiAdPlugin,
});
